[pytest]
asyncio_mode = auto
env_files = .env.test
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --tb=short -v --cov=app --cov-report=term-missing
